SKILLS = [
    "python",
    "java",
    "javascript",
    "c",
    "c++",
    "c#",
    "html",
    "css",
    "bootstrap",
    "react",
    "angular",
    "node.js",
    "django",
    "flask",
    "fastapi",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data science",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "git",
    "github",
    "docker",
    "aws",
]